services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend_c
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    networks:
      - app-network

  db:
    image: postgres:16.3
    container_name: db
    restart: always
    volumes:
      - postgress-db:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - '5432:5432'
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - app-network

volumes:
  postgress-db:  

networks:
  app-network: