services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app-network"
      - "traefik.http.routers.frontend.rule=Host(`rtmdemos.name.ng`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend-secure.rule=Host(`rtmdemos.name.ng`)"
      - "traefik.http.routers.frontend-secure.entrypoints=websecure"
      - "traefik.http.routers.frontend-secure.tls=true"
      - "traefik.http.routers.frontend-secure.tls.certresolver=letsencryptresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.frontend.middlewares=redirect-to-https"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"

  backend:
    build: ./backend
    container_name: backend_c
    restart: unless-stopped
    depends_on:
      - traefik
      - postgres
    env_file:
      - ./backend/.env
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app-network"
      - "traefik.http.routers.backend-api.rule=Host(`rtmdemos.name.ng`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-api.entrypoints=web"
      - "traefik.http.routers.backend-api-secure.rule=Host(`rtmdemos.name.ng`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-api-secure.entrypoints=websecure"
      - "traefik.http.routers.backend-api-secure.tls=true"
      - "traefik.http.routers.backend-api-secure.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.backend-docs.rule=Host(`rtmdemos.name.ng`) && PathPrefix(`/docs`)"
      - "traefik.http.routers.backend-docs.entrypoints=web"
      - "traefik.http.routers.backend-docs-secure.rule=Host(`rtmdemos.name.ng`) && PathPrefix(`/docs`)"
      - "traefik.http.routers.backend-docs-secure.entrypoints=websecure"
      - "traefik.http.routers.backend-docs-secure.tls=true"
      - "traefik.http.routers.backend-docs-secure.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.backend-redoc.rule=Host(`rtmdemos.name.ng`) && PathPrefix(`/redoc`)"
      - "traefik.http.routers.backend-redoc.entrypoints=web"
      - "traefik.http.routers.backend-redoc-secure.rule=Host(`rtmdemos.name.ng`) && PathPrefix(`/redoc`)"
      - "traefik.http.routers.backend-redoc-secure.entrypoints=websecure"
      - "traefik.http.routers.backend-redoc-secure.tls=true"
      - "traefik.http.routers.backend-redoc-secure.tls.certresolver=letsencryptresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.backend-api.middlewares=redirect-to-https"
      - "traefik.http.routers.backend-docs.middlewares=redirect-to-https"
      - "traefik.http.routers.backend-redoc.middlewares=redirect-to-https"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  postgres:
    image: postgres:16.3
    container_name: postgres_c
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
    volumes:
      - postgress-db:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - '5432:5432'
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
      - traefik
    networks:
      - app-network
    env_file:
      - ./backend/.env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app-network"
      - "traefik.http.routers.adminer.rule=Host(`db.rtmdemos.name.ng`)"
      - "traefik.http.routers.adminer.entrypoints=web"
      - "traefik.http.routers.adminer-secure.rule=Host(`db.rtmdemos.name.ng`)"
      - "traefik.http.routers.adminer-secure.entrypoints=websecure"
      - "traefik.http.routers.adminer-secure.tls=true"
      - "traefik.http.routers.adminer-secure.tls.certresolver=letsencryptresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.adminer.middlewares=redirect-to-https"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

  traefik:
    image: traefik:v3.0.4
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencryptresolver.acme.tlschallenge=true
      - --certificatesresolvers.letsencryptresolver.acme.email=rtmabiola@gmail.com
      - --certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencryptresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --accesslog
      - --api
      - --log
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    env_file:
      - ./.env
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app-network"
      - "traefik.http.routers.traefik.rule=Host(`proxy.rtmdemos.name.ng`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik-secure.rule=Host(`proxy.rtmdemos.name.ng`)"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=letsencryptresolver"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=redirect-to-https"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

volumes:
  postgress-db:
  letsencrypt:

networks:
  app-network:
    external: true