services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '5173:5173'
    stdin_open: true
    tty: true
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    networks:
      - app-network
    labels:
      - "traefik.http.routers.site.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
    depends_on:
      - traefik

  backend:
    build: ./backend
    container_name: backend_c
    restart: unless-stopped
    depends_on:
      - db
      - traefik
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    networks:
      - app-network
    labels:
      - "traefik.http.routers.site.rule=(Host(`${DOMAIN}`) && PathPrefix(`/docs`))"
      - "traefik.http.routers.site.rule=(Host(`${DOMAIN}`) && PathPrefix(`/redoc`))"
      - "traefik.http.routers.site.rule=(Host(`${DOMAIN}`) && PathPrefix(`/api`))"

  db:
    image: postgres:16.3
    container_name: db
    restart: always
    volumes:
      - postgress-db:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - '5432:5432'
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
      - traefik
    ports:
      - 8080:8080
    networks:
      - app-network
    labels:
      - "traefik.http.routers.site.rule=Host(`db.${DOMAIN}`)" 

  traefik:
    image: traefik:v3.0.4
    command: --api.insecure=true --providers.docker
    ports:
      - '80:80'
      - '443:443'
      - '8090:8090'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    env_file:
      - ./backend/.env
    labels:
      - "traefik.http.routers.site.rule=Host(`proxy.${DOMAIN}`)"

volumes:
  postgress-db:  
  letsencrypt:

networks:
  app-network: